# vim: ft=yaml.ansible
---
aap_organizations:
  - name: EDA-SK Demo
    galaxy_credentials: Ansible Galaxy

controller_settings:
  - name: AWX_COLLECTIONS_ENABLED
    value: true

  - name: AWX_ROLES_ENABLED
    value: true

controller_projects:
  - name: Demo Project
    state: absent

  - name: EDA-SK GitOps
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

  - name: EDA-SK GitOps Inventory
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

controller_credentials:
  - name: Hashivault
    description: In-Cluster Hashicorp vault lookup
    organization: EDA-SK Demo
    credential_type: HashiCorp Vault Secret Lookup
    inputs:
      url: "{{ secrets['vault_url'] }}"
      token: "{{ secrets['vault_root_token'] }}"
      cacert: "{{ secrets['vault_ca'] }}"
      api_version: v2

controller_inventory_sources:
  - name: Event-Driven Ansible Starter Kit Static Inventory
    inventory: Event-Driven Ansible Starter Kit Inventory
    organization: EDA-SK Demo
    source: scm
    source_project: EDA-SK GitOps
    source_path: inventory
    update_on_launch: true

controller_inventories:
  - name: Event-Driven Ansible Starter Kit Inventory
    organization: EDA-SK Demo

  - name: Event-Driven Ansible Starter Kit Localhost
    organization: EDA-SK Demo
    kind: smart
    host_filter: name__icontains=localhost
    inventory: Event-Driven Ansible Starter Kit Static Inventory

controller_templates:
  - name: Demo Job Template
    state: absent

  - name: Ping
    organization: EDA-SK Demo
    project: EDA-SK GitOps
    job_type: run
    inventory: Event-Driven Ansible Starter Kit Localhost
    execution_environment: Default execution environment

eda_projects:
  - name: EDA-SK GitOps
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

eda_credentials:
  - name: Controller Token
    description: AAP Access Credentials
    organization: EDA-SK Demo
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username | default('admin') }}"
      password: "{{ aap_password }}"
      verify_ssl: "{{ aap_validate_certs }}"

  - name: Basic Auth Credential
    inputs:
      username: '{{ basic_user }}'
      password: '{{ basic_password }}'
    credential_type: Basic Event Stream
    organization: EDA-SK Demo

eda_decision_environments:
  - name: EDA-SK Default Decision Environment
    organization: EDA-SK Demo
    credential: Ansible Galaxy
    image_url: registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest

eda_event_streams:
  - name: Deployment Check Event Stream
    forward_events: true
    credential_name: Basic Auth Credential
    organization: EDA-SK Demo

eda_rulebook_activations:
  - name: Dummy Debug Rulebook
    description: Dummy Rulebook that only does debug
    project: EDA-SK GitOps
    organization: EDA-SK Demo
    rulebook: dummy_debug.yml
    decision_environment: EDA-SK Default Decision Environment
    log_level: debug
    restart_policy: always
    event_streams:
      - event_stream: Deployment Check Event Stream
        source_name: Dummy Webhook entry
