# vim: ft=yaml.ansible
---
aap_organizations:
  - name: EDA-SK Demo
    galaxy_credentials: Ansible Galaxy

controller_settings:
  - name: AWX_COLLECTIONS_ENABLED
    value: true

  - name: AWX_ROLES_ENABLED
    value: true

controller_projects:
  - name: Demo Project
    state: absent

  - name: EDA-SK GitOps
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

  - name: EDA-SK GitOps Inventory
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

controller_credentials:
  - name: Hashivault
    description: In-Cluster Hashicorp vault lookup
    organization: EDA-SK Demo
    credential_type: HashiCorp Vault Secret Lookup
    inputs:
      url: "{{ secrets['vault_url'] }}"
      token: "{{ secrets['vault_root_token'] }}"
      cacert: "{{ secrets['vault_ca'] }}"
      api_version: v2

controller_templates:
  - name: Demo Job Template
    state: absent

eda_projects:
  - name: EDA-SK GitOps
    organization: EDA-SK Demo
    scm_branch: main
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "yes"
    scm_url: https://github.com/validatedpatterns-demos/rhvp.eda_starter_kit.git
    wait: true
    update_project: true

eda_credentials:
  - name: Basic Auth Credential
    username: '{{ basic_user }}'
    password: '{{ basic_password }}'
    credential_type: Basic Event Stream

eda_event_streams:
  - name: Deployment Check Event Stream
    forward_events: true
    credential_name: Basic Auth Credential
    
